items:
  1:
    Name: "1"
    Id: "276"
    Data: 0
    Lores:
      - "&0ycpsd"
    Unbreakable: true
item1:
  id: "276"
  data: 0
  name: "{rl:{rf:装备品质}颜色}† {rl:{rf:装备品质}颜色}{rl:{rf:装备品质}前缀}&8 ▪ &f训练片手刀 &8{{rl:{rf:特殊后缀}后缀颜色}{rf:特殊后缀}&8}"
  lores:
    - "&0ycpsd"
    - " &7&l[&8&m-------------♋-------------&7&l]"
    - "  &7类型 &8>&7>&f> &f片手刀"
    - "  &7品质&7: &8[{rl:{rf:装备品质}颜色}{rf:装备品质}&8]"
    - "  &7可强化次数&7: &6{rl:{rf:装备品质}强化次数}"
    - "  &7攻击速度: &61.5/s"
    - " &7&l[&8&m-------------♋-------------&7&l]"
    - "  &5† &7元素"
    - "    &7▪ &8[&7无&8]"
    - ""
    - "  &f† &7属性"
    - "    &7▪ &7基础伤害&7: &7{ri:10_10}.{ri:1_9}"
    - "    &7▪ &7破甲几率&7: &a+ &7{ri:5_12}%"
    - "{rl:原初伤害属性}"
    - ""
    - "  &a† &7前缀词条"
    - "{rl:{rf:装备品质}原初前缀1}"
    - "{rl:{rf:装备品质}原初前缀2}"
    - "{rl:{rf:装备品质}原初前缀3}"
    - "{rl:{rf:装备品质}原初前缀4}"
    - ""
    - "  &a† &7后缀词条"
    - "{rl:{rf:装备品质}原初后缀1}"
    - "{rl:{rf:装备品质}原初后缀2}"
    - "{rl:{rf:装备品质}原初后缀3}"
    - "{rl:{rf:装备品质}原初后缀4}"
    - ""
    - "  &c† &7需求"
    - "    &7▪ &7需要等级&7: &c1"
    - "    &7▪ &7需要片手刀专精&7: &c1"
    - " &7&l[&8&m-------------♋-------------&7&l]"
    - "    &7◈ &8[&7可组装&8(&f刀片&8)&8]"
    - " &7&l[&8&m-------------♋-------------&7&l]"
    - "  &7耐久值: &62000&7/&62000"
  unbreakable: true
  color: "10,20,50"